"""
Django settings for doctors_appointment project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

<<<<<<< HEAD
import os
=======
>>>>>>> 98ca75c130f9cf6c22b7c0b3a95afd4a294c4972
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v$zu3k_g_p2dp_!2*hw!m1w2%dsl@q#&uld&7ad(wzdv#u=#*^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
<<<<<<< HEAD
    'users',
    'payments',
    'doctors',
    'bookings',
    'hospitals',
    'registrations',
    'notifications',
    'reports',
    'reviews',
    'dashboard',
    'patients',
    'home',
    'blog',
    'menu_generator',
=======
>>>>>>> 98ca75c130f9cf6c22b7c0b3a95afd4a294c4972
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'doctors_appointment.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
<<<<<<< HEAD
        'DIRS': [BASE_DIR/ 'templates'],
=======
        'DIRS': [],
>>>>>>> 98ca75c130f9cf6c22b7c0b3a95afd4a294c4972
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'doctors_appointment.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
<<<<<<< HEAD
	'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'doctor_appointment',
        'USER': 'root',
        'PASSWORD': '',
        'HOST': 'localhost',
        'PORT': '54321',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'isolation_level': 'read committed',
        },
    }


    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
}


AUTH_USER_MODEL='users.CustomUser'

=======
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


>>>>>>> 98ca75c130f9cf6c22b7c0b3a95afd4a294c4972
# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
<<<<<<< HEAD


STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, '/static')





STATICFILES_DIRS = [os.path.join(BASE_DIR, 'doctors_appointment/static')]





MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')




=======
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
>>>>>>> 98ca75c130f9cf6c22b7c0b3a95afd4a294c4972

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
<<<<<<< HEAD




####################################################################################
# Example: settings.py
####################################################################################

NAV_MENU_TOP = [
    {
        "name": "FAQ",
        "url": "/",
    },
    {
        "name": "About",
        "url": "/about",
    },
    {
        "name": "Pricing Plan",
        "url": "/about",
    },
    {
        "name": "Pages",
        "url": "/",
        
        "submenu": [
            {
                "name": "About Us",
                "url": "/",
            },
            {
                "name": "Contact Us",
                "url": "/",

            },
            {
                "name": "Terms & Condition",
                "url": "/",

            },
            {
                "name": "Privacy Policy",
                "url": "/",

            }
        ],
    },
    {
        "name": "Blog",
        "url": "/blog",
    },
]



FOOTER_MENU_ONE = [
    {
        "name": "Contact Us",
    },
]

FOOTER_MENU_RIGHT = [
    {
        "name": "Address",
        "url": "/address",
    },
]
=======
>>>>>>> 98ca75c130f9cf6c22b7c0b3a95afd4a294c4972
